repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-merge-conflict
      - id: end-of-file-fixer
      - id: trailing-whitespace
      - id: check-symlinks
  - repo: https://github.com/adambrenecki/pre-commit-python-sorter
    rev: 1.0.5
    hooks:
      - id: python-import-sorter
        args: ['--silent-overwrite']
  - repo: https://github.com/psf/black
    rev: 19.3b0
    hooks:
      - id: black
  - repo: https://github.com/asottile/blacken-docs
    rev: v1.3.0
    hooks:
      - id: blacken-docs
