repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v2.3.0
  hooks:
  - id: end-of-file-fixer
  - id: trailing-whitespace
- repo: https://github.com/psf/black
  rev: 19.3b0
  hooks:
  - id: black
- repo: https://github.com/adambrenecki/pre-commit-python-sorter
  rev: 1.0.5
  hooks:
  - id: python-import-sorter
    args: ['--silent-overwrite']
- repo: https://github.com/asottile/blacken-docs
  rev: v1.3.0
  hooks:
  - id: blacken-docs
- repo: https://github.com/syntaqx/git-hooks
  rev: v0.0.16
  hooks:
  - id: shellcheck
